#-----
# main
#-----
logging:
    level: 'debug' #  *logging* module levels
    format: '%(asctime)s  %(message)s'
    handlers:
        gray_gelf: ['graylog2.domain.org', 12201] #  host and port pair
        file: False #  /full/path/to/file
        stream: True #  Bool, log to STDOUT or not

redis:
    unix_socket_path: '/var/run/redis/redis.sock'
    db: 1

arts_upload_path: '/opt/lunaport/artefacts'

#------------
# Remote APIs
#------------
lunaport:
    fqdn: 'lunaport.domain.org'
    to: 20.0
    auth: ['{user}', '{passwd}']  # HTTP Basic

email:
    dst_host: '127.0.0.1'
    dst_port: 25
    #auth: ['login', 'passwd']

xmpp:
    jid: 'user@domain.org'
    passwd: '{xmpp_passwd}'

issue_providers:
    jira:
        fqdn: 'jira-api.domain.org'
        to: 60.0
        oauth: '{firebat_oauth}'
#-----------
# monitoring
#-----------
sentry_dsn: '{PROTOCOL}://{PUBLIC_KEY}:{SECRET_KEY}@{HOST}/{PATH}{PROJECT_ID}'
